### ISSUE TITLE
Not hitting a breakpoint when going to bar

### ISSUE THREAD

**Issue by santosh** [suzmue/gophercon#2]
OS: Windows
Go: 1.17.2

I was going through your talk on the gophercon and follow along. Somehow I'm not encountering any breakpoint when visit the bar. Same with the gym.

I have cloned this version of code. https://github.com/suzmue/gophercon/tree/ffabae99c43a511fe7e53451aa3761d639012a69

**Comment by suzmue** [comment]
Hi @santosh !
Could you add "showLog": "true", "logOutput": "dap" to the launch configuration and attach the contents of the Debug Console?

**Comment by santosh** [comment]
Thanks for your response. 

Not sure what made it work. But it is working now. I'll post the logs if it happens again.
